name: cargo-clippy
run-name: cargo clippy
on: [push]
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy